### ISSUE TITLE
no typescript support

### ISSUE THREAD

**Issue by nadavten** [tarunbatra/password-validator#10]

**Comment by tarunbatra** [comment]
Hey @nadavten, thanks for taking the time. Can you elaborate on what do you mean?

**Comment by nadavten** [comment]
missings types (@types) for typescript. no intellisence

**Comment by tarunbatra** [comment]
A good feature to have! But I won't be able to add that, as I'm not much aware of Typescript / VSCode.
Keeping the issue open, in case someone would want to submit a PR for this feature.

**Comment by wbhob** [comment]
I will rise to the occasion! If it's ok with you @tarunbatra , I will rewrite in TypeScript, and include build and test scripts. It's very similar to other Object oriented languages, and instead of appending to the `prototype`, it will simply be a property on a class. PR coming shortly.

**Comment by wbhob** [comment]
Done!

**Comment by wbhob** [comment]
Done (again!)

**Comment by tarunbatra** [comment]
VScode is able to show methods available, their signature and description using JsDoc. This has inspired Issue #13. Closing this issue, hence.
