### ISSUE TITLE
What about add a validation rule for repeating chars?

### ISSUE THREAD

**Issue by fabiobeoni** [tarunbatra/password-validator#14]
Hi,
first of all thanks for this module, really useful and easy to use.

Have you any plan to add an extra validation rule, to check if the password contains a character repeated more than X time?

Thanks, cheers.
Fabio

**Comment by tarunbatra** [comment]
Hey @fabiobeoni, thanks for your interest.

There's is an option to pass regex as param in `has` method. So if your use-case can be represented in a regex, it can be used with the module. Just use it like `has(/regex/)`.

I also want to add a feature like `digits(10)` to force presence of 10 digits, or so. But I'm not getting time on my hands. Hope the above solution works for you!

**Comment by fabiobeoni** [comment]
OK I will check it, many thanks.

By the way really useful module ;) Cheers.

On 16 Jan 2018 5:29 pm, "Tarun Batra" <notifications@github.com> wrote:

Hey @fabiobeoni <https://github.com/fabiobeoni>, thanks for your interest.

There's is an option to pass regex as param in has method. So if your
use-case can be represented in a regex, it can be used with the module.
Just use it like has(/regex/).

I also want to add a feature like digits(10) to force presence of 10
digits, or so. But I'm not getting time on my hands. Hope the above
solution works for you!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tarunbatra/password-validator/issues/14#issuecomment-358020120>,
or mute the thread

**Comment by tarunbatra** [comment]
Thanks. appreciate your feedback.
