### ISSUE TITLE
has().not().uppercase() not working as expected

### ISSUE THREAD

**Issue by RhisiartK** [tarunbatra/password-validator#28]
I tried to validate only lowercase words with the rule: has not uppercase.

has().not().uppercase() - not working for 'joke' word
has().not().symbol() - works as expected

Can I use the has().not().uppercase() or I have to use regex for this?

Example: https://codesandbox.io/s/crazy-wind-vej50?fontsize=14

**Comment by tarunbatra** [comment]
Hey @RhisiartK thanks for raising the issue. I found out `not()` was not being respected in `uppercase()` and `lowercase()` since `v4.1.2`. Fixed it in `v5.0.2`.

**Comment by RhisiartK** [comment]
Thanks for the very quick answer and fix.
