### ISSUE TITLE
ERROR in ./~/password-validator/errors.json

### ISSUE THREAD

**Issue by zacksiri** [tarunbatra/password-validator#3]
I'm getting an error after upgrading to 2.1.1

```
ERROR in ./~/password-validator/errors.json
```

had to downgrade to 2.1.0 to get the build to pass.

**Comment by tarunbatra** [comment]
@zacksiri Thanx for reporting the issue.

It's correct that in `v2.1.1`, I made some changes how errors are handled in the package. But I'm not able to reproduce this error.

Can you provide more details like your `node` and `npm` version, and exact error which you're receiving?
