### ISSUE TITLE
How to set symbol set?

### ISSUE THREAD

**Issue by callow** [tarunbatra/password-validator#30]
For AWS cognito , the + and = are not regarded as special characters. 
for this API symbol() , how to specify the special character set which excludes + and = ?

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html

**Comment by tarunbatra** [comment]
`.not` rule takes optional RegEx as argument. So you can add a rule like `.not([/\+=]+/)` to ensure `+` and `=` are not being included in the password even though `.symbols` rule allows them.

**Comment by callow** [comment]
@tarunbatra 
This may not solve my issue , because , + and = can still exist as a normal character(non special characters) in the password,not total removed. I need another special characters to fill in.

**Comment by tarunbatra** [comment]
Whatever Regex is applied to `not()`, it's applicable globally.
Eg:
```
const PasswordValidator = require('password-validator');
const schema = new PasswordValidator();
schema
    .has().symbols()
    .not(/[\+=]+/);
    
console.log(schema.validate('Test@123')); // true
console.log(schema.validate('Test+123')); // false
```
Check [this runkit](https://runkit.com/embed/zris7ebl0o8n) out.

**Comment by tarunbatra** [comment]
Closing this issue since it looks like your query is resolved.
