### ISSUE TITLE
Release a new version with typings or push them to DefinitelyTyped

### ISSUE THREAD

**Issue by bbenoist** [tarunbatra/password-validator#32]
Hi there!

If you don't mind, could you please release a new minor version with the TS typings you've recently added?

If no, can it be pushed on https://github.com/DefinitelyTyped/DefinitelyTyped in the meantime so that we could use password-validator types with `@types/password-validator`?

Thanks :)

**Comment by tarunbatra** [comment]
Hey, pushed [v5.0.3](https://github.com/tarunbatra/password-validator/releases/tag/v5.0.3) with typings. Thanks for pointing it out.
