### ISSUE TITLE
Syntax error in IE11

### ISSUE THREAD

**Issue by samboylett** [tarunbatra/password-validator#34]
The module exposes ES6 which does not work in IE11, resulting in a syntax error

Solution: Transpile the module to ES5

**Comment by tarunbatra** [comment]
We have supported IE till v4 and the idea behind v5 was to use ES6. Also, I don't like transpiled code. More on that [here](https://www.freecodecamp.org/news/you-might-not-need-to-transpile-your-javascript-4d5e0a438ca/). So please feel free to use [v4.1.2](https://github.com/tarunbatra/password-validator/blob/master/CHANGELOG.md#412) or a forked version.
